import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from grafik import grafik_distribusi, pertanyaan_1, pertanyaan_2, pertanyaan_3, pertanyaan_4
import streamlit as st
from correlation import pearson, pointbiserial, phi_coefficient, crammersv
import os

script_dir = os.path.dirname(os.path.realpath(__file__))

# Preparing Dataset
day_df   = pd.read_csv(f'{script_dir}/day.csv', index_col = 'instant')
hour_df  = pd.read_csv(f'{script_dir}/hour.csv', index_col = 'instant')
day_dash  = pd.read_csv(f'{script_dir}/day_ori_scale.csv',  index_col = 'instant')
hour_dash = pd.read_csv(f'{script_dir}/hour_ori_scale.csv', index_col = 'instant')

day_dist  = grafik_distribusi(day_dash)
hour_dist = grafik_distribusi(hour_dash)

menu = st.sidebar.selectbox('Pilih Menu:', ['Introduction', 'Exploratory Data Analysis', 'Explanatory Dashboard'])

st.title('Tugas Analisis Data dengan Python')

if menu == 'Introduction' :
    st.header('Introduction')
    
    st.image(f'{script_dir}/images/images1.jpg')
    
    st.write('')
    st.markdown(f'''
                            <div style="text-align: justify;">  
                            <strong>Dataset Information</strong> 
                            
                            Bike sharing systems are new generation of traditional bike rentals where whole process from membership, rental and return back has become automatic. Through these systems, user is able to easily rent a bike from a particular position and return back at another position. Currently, there are about over 500 bike-sharing programs around the world which is composed of over 500 thousands bicycles. Today, there exists great interest in these systems due to their important role in traffic, environmental and health issues.
                            Apart from interesting real world applications of bike sharing systems, the characteristics of data being generated by these systems make them attractive for the research. Opposed to other transport services such as bus or subway, the duration of travel, departure and arrival position is explicitly recorded in these systems. This feature turns bike sharing system into a virtual sensor network that can be used for sensing mobility in the city. Hence, it is expected that most of important events in the city could be detected via monitoring these data.
                            
                            </div>''', unsafe_allow_html = True)
    
    st.markdown(f'''    
                        **Attribute Information**  
                        Both hour.csv and day.csv have the following fields, except hr which is not available in day.csv
                        
                        |Columns    |Value                                                                                                                                     |
                        |-----------|------------------------------------------------------------------------------------------------------------------------------------------|
                        |instant    |record index                                                                                                                              |
                        |dteday     |date                                                                                                                                      |
                        |season     |season (1:springer, 2:summer, 3:fall, 4:winter)                                                                                           |
                        |yr         |year (0 : 2011, 1 : 2012)                                                                                                                 |
                        |mnth       |month ( 1 to 12)                                                                                                                          |
                        |hr         |hour (0 to 23)                                                                                                                            |
                        |holiday    |weather day is holiday or not (extracted from [Web Link])                                                                                 |
                        |weekday    |day of the week                                                                                                                           |
                        |workingday |if day is neither weekend nor holiday is 1, otherwise is 0.                                                                               |
                        |weathersit |1  Clear, Few clouds, Partly cloudy, Partly cloudy                                                                                        |
                        |           |2  Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist                                                                           |
                        |           |3  Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds                                                |
                        |           |4  Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog                                                                             |
                        |temp       |Normalized temperature in Celsius. The values are derived via (t-t_min)/(t_max-t_min), t_min=-8, t_max=+39 (only in hourly scale)         |
                        |atemp      |Normalized feeling temperature in Celsius. The values are derived via (t-t_min)/(t_max-t_min), t_min=-16, t_max=+50 (only in hourly scale)|
                        |hum        |Normalized humidity. The values are divided to 100 (max)                                                                                  |
                        |windspeed  |Normalized wind speed. The values are divided to 67 (max)                                                                                 |
                        |casual     |count of casual users                                                                                                                     |
                        |registered |count of registered users                                                                                                                 |
                        |cnt        |count of total rental bikes including both casual and registered                                                                          |  
                        
                        for further more information please go through the following link,
                        http://archive.ics.uci.edu/ml/datasets/Bike+Sharing+Datase
                        
                        ''')
        
elif menu == 'Exploratory Data Analysis' :
    
    st.header('Exploratory Data Analysis')
    
    eda_day_tab, eda_hour_tab = st.tabs(['day_df', 'hour_df'])

    tab_name = [eda_day_tab, eda_hour_tab] 
    dataset  = [day_dash, hour_dash]
    dist     = [day_dist, hour_dist]
    
    options = ['---', "Descriptive Statistics", "Data Distribution", "Aggregation Analysis", "Correlation"]
    
    for i, (tab, data, distr) in enumerate(zip(tab_name, dataset, dist)) :
        
        with tab :
            st.write(data)

            st.write('Information')
            
            selected_option = st.selectbox("Pilih salah satu opsi :", options, index = 0)

            with st.container():
                if selected_option == options[1] :
                    st.write(data.describe())

                    st.write('**Insights**')
                    if i == 0 :
                        st.markdown('''
                                    - **Temperatur**  
                                        Rata-rata temperatur (temp) adalah 20.31°C, dengan rentang dari 2°C hingga 35°C.
                                    - **Temperatur Terasa**  
                                        Rata-rata temperatur terasa (atemp) adalah 23.74°C, menunjukkan bahwa suhu yang dirasakan lebih tinggi daripada suhu aktual.
                                    
                                    - **Kelembapan**    
                                        Rata-rata kelembapan (hum) adalah 62.82%, dengan nilai minimum 20% dan maksimum 97%, menunjukkan variasi kelembapan yang signifikan.
                                    - **Kecepatan Angin**  
                                        Rata-rata kecepatan angin (windspeed) adalah 12.73, dengan rentang dari 2 hingga 26, menunjukkan kondisi yang mendukung penggunaan.
                                    - **Pengguna Kasual**    
                                        Rata-rata pengguna kasual adalah 848, dengan maksimum mencapai 3410, menunjukkan lonjakan penggunaan pada kondisi tertentu.
                                    - **Pengguna Terdaftar**  
                                        Rata-rata pengguna terdaftar adalah 3656, menunjukkan loyalitas yang tinggi di antara pengguna terdaftar.
                                    - **Total Pengguna**    
                                        Rata-rata total pengguna (cnt) adalah 4504, menunjukkan tingginya penggunaan layanan.
                                    - **Variasi Penggunaan**    
                                        Standar deviasi total pengguna (cnt) adalah 1937, menunjukkan adanya variasi yang signifikan dalam pola penggunaan.''')
                    else :
                        st.markdown('''
                                    - **Jam (hr)**  
                                        Rata-rata jam penggunaan adalah 11.55, dengan rentang dari 0 hingga 23, menunjukkan data mencakup penggunaan sepanjang hari.

                                    - **Temperatur**  
                                        Rata-rata temperatur (temp) adalah 20.36°C, dengan nilai minimum 1°C dan maksimum 41°C, menunjukkan variasi suhu yang signifikan.
                                    - **Temperatur Terasa**  
                                        Rata-rata temperatur terasa (atemp) adalah 23.79°C, menunjukkan bahwa suhu yang dirasakan cenderung lebih tinggi.
                                    - **Kelembapan**  
                                        Rata-rata kelembapan (hum) adalah 62.73%, dengan kisaran antara 3% hingga 100%, menunjukkan kelembapan yang bervariasi.
                                    - **Kecepatan Angin**  
                                        Rata-rata kecepatan angin (windspeed) adalah 12.64, dengan nilai maksimum 32, menunjukkan kondisi yang umumnya mendukung penggunaan.
                                    - **Pengguna Kasual**  
                                        Rata-rata pengguna kasual adalah 35.68, dengan maksimum 367, menunjukkan adanya lonjakan penggunaan pada jam-jam tertentu.
                                    - **Pengguna Terdaftar**  
                                        Rata-rata pengguna terdaftar adalah 153.79, dengan maksimum 886, menunjukkan loyalitas di antara pengguna terdaftar.
                                    - **Total Pengguna**  
                                        Rata-rata total pengguna (cnt) adalah 189.46, menunjukkan pola penggunaan yang cukup konsisten.
                                    - **Variasi Penggunaan**  
                                        Standar deviasi total pengguna (cnt) adalah 181.39, menunjukkan adanya variasi dalam pola penggunaan berdasarkan waktu.
                                    
                                    ''')

                elif selected_option == options[2] :
                    st.write(distr)
                    
                    st.write('**Insights**')
                    if i == 0 :
                        st.markdown('''
                                    - **Skewness (Skew)**  
                                        - **Temperatur (temp)**    
                                            -0.05, menunjukkan distribusi mendekati simetris.

                                        - **Temperatur Terasa (atemp)**    
                                            -0.14, juga mendekati simetris dengan sedikit kemiringan ke kiri.
                                        - **Kelembapan (hum)**    
                                            0.01, menunjukkan distribusi hampir simetris.
                                        - **Kecepatan Angin (windspeed)**  
                                            0.55, menunjukkan distribusi miring ke kanan, dengan potensi lonjakan penggunaan pada kecepatan angin lebih tinggi.
                                        - **Pengguna Kasual (casual)**  
                                            1.27, menunjukkan distribusi miring ke kanan, mengindikasikan adanya nilai ekstrim atau lonjakan pengguna kasual.
                                        - **Pengguna Terdaftar (registered)**  
                                            0.04, menunjukkan distribusi hampir simetris.
                                        - **Total Pengguna (cnt)**    
                                            -0.05, menunjukkan distribusi mendekati simetris.

                                    - **Kurtosis (Kurt)**

                                        - **Temperatur (temp)**   
                                            -1.12, menunjukkan distribusi yang lebih datar dibandingkan distribusi normal.

                                        - **Temperatur Terasa (atemp)**  
                                            -0.99, juga menunjukkan distribusi yang lebih datar.
                                        - **Kelembapan (hum)**  
                                            -0.41, menunjukkan distribusi lebih datar dengan nilai ekstrem yang lebih sedikit.
                                        - **Kecepatan Angin (windspeed)**  
                                            -0.07, menunjukkan distribusi hampir normal.
                                        - **Pengguna Kasual (casual)**  
                                            1.32, menunjukkan distribusi yang lebih tajam dengan lebih banyak nilai ekstrim.
                                        - **Pengguna Terdaftar (registered)**    
                                            -0.71, menunjukkan distribusi yang lebih datar.
                                        - **Total Pengguna (cnt)**  
                                            -0.81, juga menunjukkan distribusi yang lebih datar.
                                    
                                    ''')
                    else :
                        st.markdown('''
                                    - **Skewness (Skew)**  
                                        - Temperatur (temp)  
                                            0.01, menunjukkan distribusi hampir simetris.  

                                        - **Temperatur Terasa (atemp)**  
                                            -0.09, sedikit miring ke kiri.
                                        - **Kelembapan (hum)**  
                                            -0.11, juga sedikit miring ke kiri.
                                        - **Kecepatan Angin (windspeed)**  
                                            0.34, menunjukkan distribusi miring ke kanan.
                                        - **Pengguna Kasual (casual)**  
                                            2.50, menunjukkan distribusi sangat miring ke kanan, dengan potensi lonjakan pengguna kasual.
                                        - **Pengguna Terdaftar (registered)**  
                                            1.56, menunjukkan distribusi miring ke kanan, tetapi tidak sekuat pengguna kasual.
                                        - **Total Pengguna (cnt)**  
                                            1.28, menunjukkan distribusi miring ke kanan, mengindikasikan lebih banyak nilai ekstrim di sisi kanan.

                                    - **Kurtosis (Kurt)**  
                                        - **Temperatur (temp)**    
                                            -0.95, menunjukkan distribusi yang lebih datar dibandingkan distribusi normal.  

                                        - **Temperatur Terasa (atemp)**    
                                            -0.87, juga menunjukkan distribusi yang lebih datar.
                                        - **Kelembapan (hum)**    
                                            -0.85, menunjukkan distribusi lebih datar.
                                        - **Kecepatan Angin (windspeed)**    
                                            -0.27, menunjukkan distribusi yang mendekati normal.
                                        - **Pengguna Kasual (casual)**    
                                            7.57, menunjukkan distribusi yang sangat tajam dengan banyak nilai ekstrem, menandakan potensi lonjakan pengguna.
                                        - **Pengguna Terdaftar (registered)**    
                                            2.75, menunjukkan distribusi yang lebih tajam dengan beberapa nilai ekstrim.
                                        - **Total Pengguna (cnt)**    
                                            1.42, menunjukkan distribusi yang tajam dengan beberapa nilai ekstrem.

                                                                        ''')
                

                elif selected_option == options[3] :
                    
                    col1, col2 = st.columns(2)
                    
                    with col1 :
                    
                        if i == 0 :
                            
                            st.write('**Analisis Distribusi Pengguna Casual vs Registered per Musim**')
                            st.dataframe(day_dash.groupby('season')[['casual', 'registered']].sum(), use_container_width = True)
                            
                            st.write('**Rata-rata Casual vs Registered per Bulan**')
                            st.dataframe(day_dash.groupby('mnth')[['casual', 'registered']].mean(), use_container_width = True)


                        else :
                            st.write('**Rata-rata Jumlah Pengguna Casual vs Registered tiap Jam**')
                            st.dataframe(hour_dash.groupby('hr')[['casual', 'registered']].mean(), use_container_width = True)
                        
                    with col2 :
                        
                        if i == 0 :
                            st.write('**Rata-rata Total Penyewaan Berdasarkan Hari tiap Tahun**')
                            st.dataframe(pd.pivot_table(index = 'weekday', columns = 'yr', values = 'cnt', aggfunc = 'mean', data = day_dash), use_container_width = True)

                            st.write('**Rata-rata Casual vs Registered tiap Musim**')
                            st.dataframe(day_dash.groupby('weathersit')[['casual', 'registered']].mean(), use_container_width = True)
                            
                            st.write('**Rata-rata Casual vs Registered untuk Hari yang merupakan Workingday vs Bukan Workingday**')
                            st.dataframe(day_dash.groupby('workingday')[['casual', 'registered']].mean(), use_container_width = True)
                            
                        else :
                            st.write('**Rata-rata Suhu, Kelembapan, dan Kecepatan Angin tiap Jam**')
                            st.dataframe(hour_dash.groupby('hr')[['temp', 'hum', 'windspeed']].mean(), use_container_width = True)
                            
                    if i == 1 :
                        st.write('**Rata-rata Total Penyewaan Berdasarkan Jam di Setiap Hari**')
                        st.dataframe(pd.pivot_table(index = 'hr', columns = 'weekday', values = 'cnt', data = hour_dash), use_container_width = True)

                            
                    st.write('**Insights**')
                    
                    if i == 0 :
                        with st.expander('**Analisis Distribusi Pengguna Casual vs Registered per Musim**') :
                            st.markdown('''
                                        
                                        - Musim panas mencatatkan jumlah pengguna registered tertinggi (715,067) dan casual (203,522). Ini menunjukkan bahwa musim panas adalah waktu puncak untuk aktivitas bersepeda, kemungkinan karena cuaca yang lebih hangat dan lebih banyak kegiatan luar ruangan
                                        - Musim dingin memiliki jumlah pengguna registered yang tinggi (711,831), meskipun jumlah casual lebih rendah (129,782). Ini menunjukkan bahwa pengguna terdaftar memiliki kecenderungan untuk tetap menggunakan sepeda bahkan dalam kondisi cuaca yang kurang ideal, mungkin karena mereka bergantung pada sepeda untuk transportasi harian

                                        - Musim semi mencatatkan jumlah pengguna casual yang paling rendah (60,622) dibandingkan dengan musim lainnya, sementara pengguna registered juga lebih rendah (410,726). Ini mungkin menunjukkan bahwa pengguna casual lebih cenderung menggunakan sepeda saat cuaca lebih hangat dan cerah, sedangkan musim semi mungkin memiliki cuaca yang lebih tidak menentu, mengurangi minat untuk bersepeda
                            ''')
                        
                        with st.expander('**Rata-rata Total Penyewaan Berdasarkan Hari tiap Tahun**') :
                            st.markdown('''
                                        - **Penyewaan Tertinggi pada Hari Jumat**  
                                            Hari Jumat memiliki angka penyewaan tertinggi di kedua tahun, dengan 3500.12 di 2011 dan 5880.46 di 2012, menunjukkan popularitas hari ini untuk penyewaan sepeda.

                                        - **Penyewaan Stabil di Awal Minggu**  
                                            Hari Senin dan Selasa menunjukkan penyewaan yang relatif tinggi dan stabil, mencerminkan kebutuhan pengguna di awal minggu, meskipun sedikit lebih rendah dibandingkan hari Jumat.

                                        - **Fluktuasi Penyewaan Akhir Pekan**  
                                            Hari Sabtu dan Minggu menunjukkan penyewaan yang lebih tinggi dibandingkan dengan hari kerja lainnya, dengan Sabtu memiliki rata-rata 3391.38 di 2011 dan 5732.00 di 2012.

                                        - **Penyewaan Terendah pada Hari Rabu**  
                                            Rata-rata penyewaan paling rendah tercatat pada hari Rabu, dengan 3253.25 di 2011 dan 5843.83 di 2012, menunjukkan bahwa hari ini mungkin kurang populer untuk penyewaan sepeda.

                                        - **Peningkatan Penyewaan di 2012**  
                                            Secara umum, terlihat adanya peningkatan penyewaan di tahun 2012 dibandingkan 2011 untuk semua hari dalam seminggu, yang menunjukkan pertumbuhan dalam penggunaan sepeda.

                                        - **Hari Kamis sebagai Alternatif Populer**  
                                            Hari Kamis mencatat penyewaan yang cukup tinggi di 2012 (5977.75), menjadikannya alternatif yang populer bagi pengguna.

                                        - **Konsistensi Penyewaan**  
                                            Rata-rata penyewaan di 2011 dan 2012 menunjukkan konsistensi dalam pola, dengan tidak banyak perubahan drastis dalam urutan hari.

                                        - **Strategi Pemasaran Hari Khusus**  
                                            Mengingat popularitas hari tertentu, strategi pemasaran dapat difokuskan pada hari Jumat dan akhir pekan untuk menarik lebih banyak penyewa.
                                    
        
                                        ''')
                        
                        with st.expander('**Rata-rata Casual vs Registered per Bulan**') :
                            st.markdown('''
                                        - **Penyewaan Tinggi di Musim Panas**  
                                            Bulan April, Juli, Agustus, dan Juni menunjukkan angka penyewaan yang tinggi untuk kedua kategori.  
                                    
                                        - **Penyewaan Terendah di Musim Dingin**  
                                            Februari dan Desember mencatat angka penyewaan yang jauh lebih rendah, terutama untuk pengguna kasual.
                                        - **Pengguna Terdaftar Dominan**  
                                            Rata-rata penyewaan untuk pengguna terdaftar jauh lebih tinggi di semua bulan, mencerminkan loyalitas.
                                        - **Fluktuasi Pengguna Kasual**   
                                            Pengguna kasual menunjukkan fluktuasi signifikan, dengan puncak di Juli dan Agustus.
                                        - **Bulan Paling Ramai**  
                                            Agustus adalah bulan dengan penyewaan tertinggi, mungkin karena acara atau aktivitas khusus.
                                        - **Penyewaan Menurun di Akhir Tahun**  
                                            Rata-rata penyewaan menurun drastis pada November dan Desember, menunjukkan pengaruh cuaca dingin.
                                        - **Pengguna Kasual Puncak di Musim Panas**    
                                            Kasual menyewa lebih banyak saat cuaca baik, dengan angka terendah di Januari dan Februari.
                                        - **Fokus pada Bulan Hangat**    
                                            Strategi pemasaran dapat lebih difokuskan pada bulan musim panas, terutama di Juli dan Agustus.
                                        - **Program Loyalitas untuk Pengguna Terdaftar**    
                                            Dapat meningkatkan retensi dan penyewaan dengan program loyalitas bagi pengguna terdaftar. 
                                    
        
                                        ''')
                        
                        with st.expander('**Rata-rata Casual vs Registered tiap Musim**') :
                            st.markdown('''
                                        - **Penyewaan Terendah pada Cuaca "Caution"**  
                                            Rata-rata penyewaan untuk pengguna kasual (185.48) dan terdaftar (1617.81) jauh lebih rendah dibandingkan dengan situasi cuaca lainnya, menunjukkan bahwa cuaca yang kurang mendukung mengurangi minat untuk menyewa sepeda.

                                        - **Penyewaan Tertinggi pada Cuaca "Normal"**  
                                            Situasi cuaca "Normal" mencatat angka tertinggi untuk kedua kategori, dengan 964.03 untuk kasual dan 3912.76 untuk terdaftar, menandakan bahwa cuaca baik sangat mendukung penyewaan sepeda.
                                        - **Penyewaan Stabil pada Cuaca "Moderate"**  
                                            Cuaca "Moderate" menunjukkan penyewaan yang cukup baik, dengan pengguna kasual mencapai 687.35 dan terdaftar 3348.51. Ini menunjukkan bahwa meskipun cuaca tidak ideal, masih ada minat yang signifikan dari pengguna.
                                        - **Perbedaan Signifikan antara Kasual dan Terdaftar**  
                                            Terdapat perbedaan yang jelas antara jumlah penyewaan pengguna kasual dan terdaftar di semua situasi cuaca, dengan pengguna terdaftar secara konsisten menyewa lebih banyak.
                                        - **Loyalitas Pengguna Terdaftar**  
                                            Angka penyewaan yang tinggi untuk pengguna terdaftar, bahkan pada cuaca "Caution," menunjukkan bahwa mereka lebih loyal dan mungkin lebih berpengalaman dalam menyesuaikan rencana penyewaan mereka berdasarkan kondisi cuaca.
                                        - **Strategi untuk Cuaca Buruk**  
                                            Mengingat rendahnya penyewaan pada cuaca "Caution," mungkin bermanfaat untuk menawarkan promosi atau insentif pada hari-hari tersebut untuk mendorong lebih banyak penyewaan.
                                        - **Fokus pada Cuaca Baik**  
                                            Untuk meningkatkan penyewaan, fokus pada promosi saat cuaca "Normal" dan "Moderate" dapat membantu menarik lebih banyak pengguna, terutama kasual.
                                        ''')
                        
                        with st.expander('**Rata-rata Casual vs Registered untuk Hari yang merupakan Workingday vs Bukan Workingday**') :
                            st.markdown('''
                                        - **Penyewaan Tinggi pada Hari Non-Kerja**  
                                            Rata-rata penyewaan untuk pengguna kasual (1371.13) dan terdaftar (2959.03) jauh lebih tinggi pada hari non-kerja (No) dibandingkan dengan hari kerja (Yes), menunjukkan bahwa banyak orang lebih memilih untuk menyewa sepeda saat tidak bekerja.

                                        - **Penyewaan Rendah pada Hari Kerja**  
                                            Pada hari kerja, pengguna kasual mencatat penyewaan yang jauh lebih rendah (606.57), meskipun pengguna terdaftar tetap menyewa lebih banyak (3978.25). Ini menunjukkan bahwa pengguna terdaftar lebih konsisten dalam menyewa sepeda, bahkan saat bekerja.

                                        - **Perbedaan Signifikan antara Kasual dan Terdaftar**  
                                            Pengguna terdaftar selalu menyewa lebih banyak dibandingkan pengguna kasual, baik pada hari kerja maupun non-kerja. Ini menunjukkan bahwa pengguna terdaftar lebih loyal dan aktif dalam menggunakan layanan.

                                        - **Preferensi Pengguna Kasual**  
                                            Tingginya angka penyewaan kasual pada hari non-kerja menunjukkan bahwa mereka mungkin menggunakan sepeda untuk rekreasi atau aktivitas sosial.

                                        - **Loyalitas Pengguna Terdaftar**  
                                            Pengguna terdaftar menunjukkan ketahanan dalam penyewaan sepeda meskipun pada hari kerja, menunjukkan bahwa mereka lebih terlibat dan mungkin mengandalkan sepeda untuk kebutuhan transportasi harian.

                                        - **Strategi Pemasaran untuk Hari Kerja**  
                                            Mengingat rendahnya penyewaan pada hari kerja untuk pengguna kasual, strategi pemasaran dapat difokuskan pada promosi di hari non-kerja, sambil tetap mempertahankan perhatian pada pengguna terdaftar di hari kerja.

                                        - **Kesempatan untuk Meningkatkan Penyewaan pada Hari Kerja**  
                                            Dengan menawarkan insentif atau program khusus untuk pengguna kasual pada hari kerja, perusahaan dapat mendorong lebih banyak penyewaan di hari-hari tersebut.
                                    ''')
                        
                    else :
                        with st.expander('**Rata-rata Jumlah Pengguna Casual vs Registered tiap Jam**') :
                            st.markdown('''
                                        - **Puncak Penyewaan pada Jam Sibuk**  
                                            Penyewaan sepeda untuk pengguna terdaftar menunjukkan puncak yang signifikan antara jam 17:00 dan 18:00, dengan 387.18, yang menunjukkan bahwa banyak pengguna terdaftar menggunakan sepeda untuk pulang kerja.

                                        - **Penyewaan Tinggi di Pagi dan Sore**  
                                            Pengguna kasual juga menunjukkan pola yang mirip, dengan puncak penyewaan di jam 8:00 (21.68) dan jam 17:00 (74.27). Ini mengindikasikan bahwa sepeda digunakan untuk perjalanan ke kantor dan aktivitas di luar.

                                        - **Penyewaan Terendah di Pagi Dini**  
                                            Penyewaan paling rendah tercatat di jam-jam pagi dini (00:00 hingga 06:00), dengan angka sangat rendah untuk kedua kategori. Ini menunjukkan bahwa pengguna cenderung tidak menyewa sepeda di waktu-waktu tersebut.

                                        - **Rata-rata Pengguna Terdaftar Lebih Tinggi**  
                                            Pada hampir setiap jam, penyewaan untuk pengguna terdaftar jauh lebih tinggi dibandingkan dengan pengguna kasual, menunjukkan tingkat keterlibatan yang lebih tinggi.

                                        - **Fluktuasi Penyewaan Sepanjang Hari**  
                                            Ada penurunan yang signifikan dalam penyewaan di antara jam-jam puncak, terutama setelah jam 19:00, ketika penyewaan mulai menurun tajam, menunjukkan bahwa pengguna lebih cenderung menyewa sepeda pada siang dan sore hari.

                                        - **Strategi Pemasaran untuk Jam Tertentu**  
                                            Dengan memahami jam-jam dengan penyewaan tinggi, strategi pemasaran dapat difokuskan untuk menarik lebih banyak penyewa, terutama selama jam-jam sibuk seperti pagi dan sore.

                                        - **Insentif untuk Pengguna Kasual di Jam Tenang**  
                                            Mungkin bermanfaat untuk menawarkan insentif atau promosi bagi pengguna kasual selama jam-jam yang kurang populer (seperti malam hari) untuk mendorong penyewaan di waktu tersebut.

                                        - **Konsistensi Penyewaan Sepeda**  
                                            Pola penyewaan menunjukkan konsistensi dalam perilaku pengguna di seluruh jam, dengan tren yang dapat diprediksi berdasarkan waktu hari.
                                    ''')
                            
                        with st.expander('**Rata-rata Suhu, Kelembapan, dan Kecepatan Angin tiap Jam**') :
                            st.markdown('''
                                        - **Pola Suhu Sepanjang Hari**  
                                            Suhu mencapai puncaknya sekitar jam 15:00 hingga 16:00, dengan nilai tertinggi mencapai 23.30°C. Ini menunjukkan bahwa suhu paling nyaman untuk aktivitas luar ruangan terjadi pada sore hari.

                                        - **Kelembapan Terendah di Sore**  
                                            Kelembapan menunjukkan tren menurun sepanjang hari, mencapai level terendah sekitar jam 14:00 hingga 15:00 (49.70% hingga 49.22%). Ini bisa menjadi waktu yang lebih nyaman untuk bersepeda.

                                        - **Kecepatan Angin yang Stabil**  
                                            Kecepatan angin cenderung stabil, tetapi sedikit meningkat dari pagi hingga sore, dengan nilai tertinggi mencapai 15.78 km/jam pada jam 16:00. Angin yang lebih kencang dapat memengaruhi kenyamanan pengguna saat bersepeda.

                                        - **Pengaruh Suhu dan Kelembapan pada Penyewaan**  
                                            Suhu yang lebih tinggi dan kelembapan yang lebih rendah pada sore hari kemungkinan berkontribusi pada meningkatnya penyewaan sepeda, karena kondisi cuaca yang lebih nyaman.

                                        - **Pagi Dini dengan Suhu Rendah**  
                                            Pada jam-jam pagi dini (00:00 hingga 06:00), suhu rendah (19.17°C hingga 17.70°C) dan kelembapan yang lebih tinggi (di atas 69%) dapat menjelaskan rendahnya penyewaan sepeda pada waktu ini.

                                        - **Kondisi Ideal di Sore Hari**  
                                            Kondisi ideal untuk bersepeda terlihat pada sore hari (jam 15:00 hingga 18:00), di mana suhu nyaman dan kelembapan rendah. Ini bisa menjadi target untuk kampanye promosi.

                                        - **Kelembapan yang Mempengaruhi Kenyamanan**  
                                            Kelembapan yang tinggi pada pagi dan sore hari dapat membuat pengalaman bersepeda kurang nyaman. Strategi untuk memberikan informasi tentang cuaca atau tips tentang bersepeda di cuaca lembap bisa bermanfaat.

                                        - **Strategi Pemasaran berdasarkan Cuaca**  
                                            Menyusun promosi atau program khusus pada waktu-waktu dengan suhu yang lebih tinggi dan kelembapan yang lebih rendah dapat meningkatkan penyewaan sepeda.
                                        
                                        ''')
                        
                        with st.expander('**Rata-rata Total Penyewaan Berdasarkan Jam di Setiap Hari**') :
                            st.markdown('''
                                        - **Puncak Penyewaan pada Sore Hari**  
                                            Penyewaan tertinggi terjadi antara jam 17:00 hingga 18:00, terutama pada hari Jumat dan Senin. Ini menunjukkan bahwa banyak orang menggunakan sepeda untuk pulang dari kerja atau beraktivitas di luar setelah jam kerja.

                                        - **Popularitas Akhir Pekan**  
                                            Hari Sabtu dan Minggu memiliki angka penyewaan yang signifikan, meskipun Minggu sedikit lebih rendah dibandingkan dengan Sabtu. Ini menunjukkan bahwa orang cenderung bersepeda untuk rekreasi di akhir pekan.

                                        - **Rendah di Pagi Dini dan Malam**  
                                            Penyewaan paling rendah tercatat pada jam-jam pagi dini (0:00 hingga 6:00) dan malam hari (22:00 hingga 23:00). Hal ini mencerminkan kurangnya aktivitas bersepeda pada waktu-waktu tersebut.

                                        - **Hari Kerja vs. Akhir Pekan**  
                                            Angka penyewaan pada hari kerja (Senin hingga Kamis) lebih rendah dibandingkan dengan akhir pekan. Namun, ada potensi untuk meningkatkan penyewaan pada hari kerja dengan menawarkan promosi atau diskon.

                                        - **Kondisi Pagi dan Siang**  
                                            Penyewaan mulai meningkat setelah jam 6:00 dan mencapai angka yang cukup baik pada jam 8:00, menunjukkan bahwa pengguna memanfaatkan sepeda untuk berangkat kerja atau beraktivitas di pagi hari.

                                        - **Fluktuasi Penyewaan**  
                                            Angka penyewaan menunjukkan fluktuasi yang signifikan sepanjang hari. Misalnya, ada lonjakan yang jelas di pagi hari (jam 8:00) dan sore hari (jam 17:00).

                                        - **Strategi Pemasaran**  
                                            Dengan memahami pola penyewaan ini, perusahaan dapat merencanakan strategi pemasaran yang lebih efektif, seperti promosi khusus pada jam dan hari dengan potensi penyewaan tinggi.

                                        - **Kesempatan untuk Meningkatkan Penyewaan di Hari Kerja**  
                                            Mengingat angka penyewaan yang lebih rendah di hari kerja, ada peluang untuk meningkatkan minat pengguna dengan menawarkan program loyalitas atau kampanye pemasaran yang ditargetkan.
                                        
                                        ''')
                        

                elif selected_option == options[4] :
                    
                    with st.container() :
                        
                        biner_col = ['yr', 'holiday', 'workingday']
                        multi_cat_col = [col for col in data.drop(columns = 'dteday').select_dtypes('object') if data[col].nunique() > 2]

                        st.write('**Korelasi Numerik-Numerik**')

                        st.dataframe(pearson(data), use_container_width = True)

                        col1, col2 = st.columns(2)

                        with col1 :

                            st.write('**Korelasi Biner-Biner**')

                            if i == 0 :
                                st.dataframe(phi_coefficient(day_df, biner_col), use_container_width = True)
                            else :
                                st.dataframe(phi_coefficient(hour_df, biner_col), use_container_width = True)
                                
                            st.write('**Korelasi Numerik-Biner**')

                            if i == 0 :
                                st.dataframe(pointbiserial(day_df), use_container_width = True)
                            else :
                                st.dataframe(pointbiserial(hour_df), use_container_width = True)

                        with col2 :
                            st.write('**Korelasi Biner-Multi Kategori**')

                            if i == 0 :
                                st.write(crammersv(day_df, biner_col, multi_cat_col))
                            else :
                                st.write(crammersv(hour_df, biner_col, multi_cat_col))
                                
                        
                            st.write('**Korelasi Multi Kategori-Multi Kategori**')

                            if i == 0 :
                                st.dataframe(crammersv(day_df, multi_cat_col, multi_cat_col), use_container_width = True)
                            else :
                                st.dataframe(crammersv(hour_df, multi_cat_col, multi_cat_col), use_container_width = True)
                        
                        st.write('**Insights**')
                        if i == 0 :
                            
                            with st.expander('Numerik-Numerik') :
                                st.markdown('''  
                                            
                                            - **Korelasi Antara Temperatur**  
                                                Temperatur (temp) dan Temperatur Terasa (atemp) : Korelasi sangat tinggi (0.99), menunjukkan bahwa keduanya berhubungan erat.

                                            - **Korelasi dengan Kelembapan**  
                                                Kelembapan (hum): Korelasi negatif dengan temperatur dan temperatur terasa, menunjukkan bahwa peningkatan kelembapan cenderung terkait dengan penurunan suhu.

                                            - **Korelasi Pengguna Kasual dan Terdaftar**  

                                              - Pengguna Kasual (casual) dan Total Pengguna (cnt) : Korelasi tinggi (0.69), menunjukkan bahwa peningkatan pengguna kasual berbanding lurus dengan total pengguna.

                                              - Pengguna Terdaftar (registered) dan Total Pengguna (cnt) : Sangat tinggi (0.97), menandakan bahwa pengguna terdaftar hampir sepenuhnya berkontribusi terhadap total pengguna.

                                            - **Korelasi dengan Kecepatan Angin**  
                                                Kecepatan Angin (windspeed) : Korelasi rendah dengan pengguna dan variabel lain, menunjukkan bahwa kecepatan angin mungkin tidak berpengaruh signifikan terhadap penggunaan layanan.

                                            - **Korelasi Antar Pengguna**  
                                                Korelasi positif moderat antara pengguna kasual dan terdaftar (0.51), menunjukkan bahwa mereka berhubungan, tetapi dengan karakteristik yang berbeda.
                            ''')
                            
                            with st.expander('Biner-Numerik') :
                                st.markdown('''

                                            - **Korelasi dengan Tahun (yr)**  

                                                - Pengguna Terdaftar (registered): Korelasi positif yang tinggi (0.59) menunjukkan bahwa jumlah pengguna terdaftar cenderung meningkat seiring berjalannya tahun.
                                                - Total Pengguna (cnt): Korelasi positif (0.57) menandakan bahwa total penggunaan juga meningkat dari tahun ke tahun.  

                                            - **Korelasi dengan Hari Libur (holiday)**  

                                                - Pengguna Kasual (casual) : Korelasi positif (0.25) menunjukkan bahwa ada kecenderungan untuk lebih banyak pengguna kasual pada hari libur.
                                                - Pengguna Terdaftar (registered) : Korelasi negatif (-0.11) menunjukkan bahwa pengguna terdaftar mungkin lebih sedikit pada hari libur, berbanding terbalik dengan pengguna kasual.

                                            - **Korelasi dengan Hari Kerja (workingday)**

                                                - Pengguna Kasual (casual) : Korelasi negatif yang kuat (-0.52) menunjukkan bahwa penggunaan oleh pengguna kasual cenderung menurun pada hari kerja.
                                                - Pengguna Terdaftar (registered) : Korelasi positif (0.30) menandakan bahwa pengguna terdaftar lebih aktif pada hari kerja dibandingkan dengan pengguna kasual.  

                                            - **Korelasi dengan Variabel Cuaca**  

                                                - Kelembapan (hum) : Korelasi negatif (-0.11) dengan tahun menunjukkan bahwa kelembapan mungkin menurun seiring waktu, tetapi tidak berpengaruh besar pada penggunaan.
                                                - Kecepatan Angin (windspeed) : Korelasi sangat rendah dengan semua variabel, menunjukkan bahwa kecepatan angin tidak banyak berpengaruh terhadap pola penggunaan.
                            ''')
                                
                            with st.expander('Biner-Biner') :
                                st.markdown('''
    
                                            - **Korelasi dengan Tahun (yr)**  

                                               - Tahun dan Hari Kerja (workingday) : Korelasi sempurna (1.00), menunjukkan bahwa semua data tahun yang sama memiliki hari kerja yang sama, ini mungkin karena desain dataset.
                                               - Tahun dan Hari Libur (holiday) : Korelasi nol (0.00), menunjukkan bahwa hari libur tidak tergantung pada tahun.
                                               - Tahun dan Situasi Cuaca (weathersit) : Korelasi rendah (0.08), menunjukkan sedikit hubungan antara tahun dan kondisi cuaca.

                                            - **Korelasi dengan Hari Libur (holiday)**
                                               
                                               - Hari Libur dan Situasi Cuaca (weathersit) : Korelasi rendah (0.04), menunjukkan bahwa kondisi cuaca tidak banyak mempengaruhi keputusan untuk merayakan hari libur.
                                               - Hari Libur dan Hari Kerja (workingday) : Korelasi moderat (0.24), menunjukkan bahwa ada beberapa hubungan antara keduanya; misalnya, hari libur mungkin lebih mungkin jatuh pada akhir pekan.

                                            - **Korelasi dengan Hari Kerja (workingday)**  
                                                Hari Kerja dan Situasi Cuaca (weathersit) : Korelasi rendah (0.06), menunjukkan bahwa kondisi cuaca tidak banyak berpengaruh terhadap hari kerja.

                                            - **Korelasi Situasi Cuaca (weathersit)**  
                                               Situasi Cuaca : Nilai 1.41 pada diagonal menunjukkan bahwa ini adalah hasil dari perhitungan varians, bukan korelasi yang dapat diinterpretasikan.
                            ''')
                                
                            with st.expander('Biner-Multi Kategori') :
                                st.markdown('''  
                                        
                                            - **Korelasi dengan Musim (season)**  
                                            
                                               - Musim : Korelasi rendah dengan tahun (0.002), menunjukkan tidak ada hubungan yang signifikan antara musim dan tahun.
                                               - Hari Libur (holiday) : Korelasi rendah (0.045), menunjukkan bahwa musim tidak banyak mempengaruhi hari libur.
                                               - Hari Kerja (workingday) : Korelasi rendah (0.03), menunjukkan bahwa musim tidak secara signifikan mempengaruhi pola hari kerja.
                                               - Situasi Cuaca (weathersit) : Korelasi moderat (0.10), menunjukkan sedikit hubungan antara musim dan kondisi cuaca.
                                            
                                            - **Korelasi dengan Bulan (mnth)**
                                            
                                               - Bulan : Korelasi rendah dengan tahun (0.004), menunjukkan bahwa bulan tidak tergantung pada tahun.
                                               - Hari Libur (holiday) : Korelasi moderat (0.12), menunjukkan bahwa ada hubungan antara bulan dan hari libur.                                            
                                               - Hari Kerja (workingday) : Korelasi rendah (0.06), menunjukkan bahwa bulan tidak banyak mempengaruhi pola hari kerja.                                            
                                               - Situasi Cuaca (weathersit) : Korelasi moderat (0.16), menunjukkan adanya pengaruh bulan terhadap kondisi cuaca.
                                            
                                            - **Korelasi dengan Hari dalam Minggu (weekday)**  
                                            
                                               - Hari dalam Minggu : Korelasi sangat tinggi dengan hari kerja (0.94), menunjukkan bahwa pola hari dalam minggu sangat berhubungan dengan status hari kerja.                                            
                                               - Hari Libur (holiday) : Korelasi moderat (0.28), menunjukkan bahwa ada hubungan antara hari dalam minggu dan kemungkinan menjadi hari libur.
                                            
                                            - **Korelasi dengan Situasi Cuaca (weathersit)**  
                                                Situasi Cuaca : Korelasi 1.00 dengan dirinya sendiri, menunjukkan hasil perhitungan varians.
                                            
                                            - **Korelasi dengan Tanggal (date)**  
                                                Tanggal : Korelasi rendah dengan tahun (0.008) dan moderat dengan hari libur (0.15), menunjukkan hubungan yang sangat terbatas dengan variabel lainnya.

                                    ''')
                            
                            with st.expander('Multi Kategori-Multi Kategori') :
                                st.markdown('''  
                                        
                                            - **Korelasi Musim (season)**  
                                               - Bulan (mnth) : Korelasi tinggi (0.90), menunjukkan bahwa terdapat hubungan kuat antara musim dan bulan, dengan kemungkinan bahwa setiap bulan terkait dengan musim tertentu.
                                               - Hari dalam Minggu (weekday) : Korelasi sangat rendah (0.01), menunjukkan bahwa tidak ada hubungan signifikan antara musim dan hari dalam minggu.
                                            
                                               - Situasi Cuaca (weathersit) : Korelasi rendah (0.10), menunjukkan sedikit hubungan antara musim dan kondisi cuaca.
                                               - Tanggal (date) : Korelasi rendah (0.04), menunjukkan bahwa musim tidak banyak berpengaruh pada tanggal.
                                            
                                            - **Korelasi Bulan (mnth)**  
                                               - Hari dalam Minggu (weekday) : Korelasi rendah (0.03), menunjukkan bahwa bulan tidak berpengaruh signifikan pada pola hari dalam minggu.
                                               - Situasi Cuaca (weathersit) : Korelasi moderat (0.16), menunjukkan bahwa bulan berpengaruh lebih pada kondisi cuaca.
                                            
                                               - Tanggal (date) : Korelasi sangat rendah (0.04), menunjukkan sedikit hubungan antara bulan dan tanggal.
                                            
                                            - **Korelasi Hari dalam Minggu (weekday)**  
                                               - Situasi Cuaca (weathersit) : Korelasi rendah (0.10), menunjukkan sedikit pengaruh antara hari dalam minggu dan kondisi cuaca.
                                               - Tanggal (date) : Korelasi rendah (0.09), menunjukkan hubungan terbatas antara hari dalam minggu dan tanggal.
                                            
                                            - **Korelasi Situasi Cuaca (weathersit)**  
                                              Tanggal (date) : Korelasi moderat (0.20), menunjukkan adanya hubungan yang lebih kuat antara situasi cuaca dan tanggal.

                                        ''')
                        else :
                            with st.expander('Numerik-Numerik') :
                                st.markdown('''  
                                            
                                            - **Korelasi dengan Jam (hr)**  

                                               - Korelasi positif dengan jumlah pengguna terdaftar (0.37) dan total pengguna (0.39), menunjukkan bahwa semakin tinggi jam, semakin banyak pengguna.
                                               - Korelasi negatif dengan kelembapan (hum) (-0.28), menunjukkan bahwa pada jam-jam tertentu dengan kelembapan yang lebih tinggi, penggunaan sepeda cenderung menurun.

                                            - **Korelasi dengan Suhu (temp)**  

                                               - Korelasi tinggi dengan suhu yang dirasakan (atemp) (0.99), menunjukkan bahwa keduanya sangat terkait.
                                               - Korelasi positif  dengan pengguna kasual (0.46) dan total pengguna (0.40), menunjukkan bahwa semakin tinggi suhu, semakin banyak pengguna.

                                            - **Korelasi dengan Suhu yang Dirasakan (atemp)**  

                                               - Sama dengan suhu, menunjukkan **korelasi positif** yang sama terhadap pengguna kasual dan total pengguna.
                                               - Keduanya juga sangat terkait dengan suhu (temp).

                                            - **Korelasi dengan Kelembapan (hum)**  
                                                Korelasi negatif yang kuat dengan pengguna kasual (-0.35) dan total pengguna (-0.32), menunjukkan bahwa meningkatnya kelembapan cenderung mengurangi penggunaan sepeda.

                                            - **Korelasi dengan Kecepatan Angin (windspeed)**  
                                                Korelasi sangat rendah dengan semua variabel, menunjukkan bahwa kecepatan angin tidak memiliki pengaruh signifikan terhadap pola penggunaan sepeda.

                                            - **Korelasi dengan Pengguna Kasual dan Terdaftar**  

                                               - Korelasi tinggi antara pengguna kasual dan pengguna terdaftar (0.51), menunjukkan bahwa ada hubungan yang signifikan antara keduanya.
                                               - Korelasi tinggi dengan total pengguna (cnt) (0.69 untuk kasual dan 0.97 untuk terdaftar), menunjukkan bahwa jumlah pengguna terdaftar cenderung sangat berhubungan dengan total pengguna.
                            ''')
                            
                            with st.expander('Biner-Numerik') :
                                st.markdown('''

                                            - **Korelasi dengan Tahun (yr)**  
                                              Sangat rendah (-0.0039), menunjukkan tidak ada hubungan signifikan antara jam dan tahun.

                                            - **Korelasi dengan Hari Libur (holiday)**  
                                               - Sangat rendah (0.0005), menunjukkan bahwa hari libur tidak berpengaruh pada pola jam penggunaan.
                                               - Korelasi negatif dengan pengguna terdaftar (-0.047), menunjukkan bahwa pengguna terdaftar sedikit menurun pada hari libur.

                                            - **Korelasi dengan Hari Kerja (workingday)**  
                                               - Sangat rendah (0.0023), menunjukkan bahwa hari kerja tidak berpengaruh signifikan terhadap penggunaan sepeda.
                                               - Korelasi negatif dengan pengguna kasual (-0.30), menunjukkan bahwa pada hari kerja, pengguna kasual cenderung berkurang.

                                            - **Korelasi dengan Suhu (temp) dan Suhu yang Dirasakan (atemp)**  
                                                Suhu (temp) dan suhu yang dirasakan (atemp) menunjukkan korelasi positif yang sangat rendah (sekitar 0.04), menunjukkan bahwa suhu tidak banyak mempengaruhi hari kerja atau hari libur.

                                            - **Korelasi dengan Kelembapan (hum)**  
                                                 Korelasi negatif dengan pengguna kasual (-0.08), menunjukkan bahwa meningkatnya kelembapan dapat mengurangi penggunaan sepeda.

                                            - **Korelasi dengan Kecepatan Angin (windspeed)**  
                                                Korelasi sangat rendah dan negatif dengan hari kerja (-0.01) dan hari libur (0.004), menunjukkan bahwa kecepatan angin tidak berpengaruh signifikan terhadap penggunaan sepeda.

                                            - **Korelasi dengan Pengguna Kasual dan Terdaftar**  
                                                Korelasi positif dengan pengguna terdaftar (0.25) dan total pengguna (cnt) (0.25), menunjukkan bahwa jumlah pengguna terdaftar cenderung berhubungan positif dengan total pengguna.
                                ''')
                                
                            with st.expander('Biner-Biner') :
                                st.markdown('''
                                            
                                            - **Korelasi Tahun (yr)**  

                                               - Korelasi sangat tinggi dengan dirinya sendiri (1.00), menunjukkan konsistensi dalam data tahun.
                                               - Korelasi rendah dengan hari libur (0.0063) dan hari kerja (0.0021), menunjukkan bahwa tahun tidak berpengaruh signifikan terhadap kategori tersebut.

                                            - **Korelasi Hari Libur (holiday)**   

                                               - Korelasi tinggi dengan dirinya sendiri (1.00), menunjukkan konsistensi dalam data hari libur.
                                               - Korelasi moderat dengan hari kerja (0.2521), menunjukkan bahwa ada hubungan antara hari libur dan hari kerja, meskipun tidak kuat.

                                            - **Korelasi Hari Kerja (workingday)**    

                                               - Korelasi tinggi dengan dirinya sendiri (1.00), menunjukkan konsistensi dalam data hari kerja.
                                               - Korelasi moderat dengan hari libur (0.2521), menunjukkan bahwa ada hubungan signifikan antara hari kerja dan hari libur.
                                ''')
                                
                            with st.expander('Biner-Multi Kategori') :
                                st.markdown('''  
                                        
                                            - **Korelasi dengan Tahun (yr)**  

                                               - Sangat rendah (0.0121) dengan musim (season), menunjukkan tidak ada hubungan signifikan antara tahun dan musim.
                                               - Korelasi rendah dengan bulan (mnth) (0.0151) dan hari (date) (0.0103), menunjukkan bahwa tahun tidak banyak mempengaruhi faktor-faktor ini.

                                            - **Korelasi dengan Hari Libur (holiday)**  

                                               - Korelasi moderat dengan hari kerja (workingday) (0.2846), menunjukkan bahwa ada hubungan antara hari libur dan hari kerja, di mana lebih banyak hari kerja berhubungan dengan lebih sedikit hari libur.
                                               - Korelasi rendah dengan musim (0.0453) dan bulan (0.1159), menunjukkan bahwa hari libur tidak berpengaruh signifikan terhadap faktor-faktor ini.

                                            - **Korelasi dengan Hari Kerja (workingday)**  

                                               - Korelasi tinggi dengan hari dalam seminggu (weekday) (0.9389), menunjukkan hubungan yang kuat; semakin banyak hari kerja, semakin tinggi kemungkinan hari-hari itu jatuh pada hari kerja.
                                               - Korelasi rendah dengan musim (0.0344) dan bulan (0.0672), menunjukkan bahwa hari kerja tidak banyak dipengaruhi oleh faktor-faktor ini.

                                            - **Korelasi dengan Cuaca (weathersit)**  

                                               - Sangat rendah dengan tahun (0.0323), menunjukkan bahwa kondisi cuaca tidak banyak dipengaruhi oleh tahun.
                                               - Korelasi rendah dengan hari libur (0.0238) dan hari kerja (0.0448), menunjukkan bahwa cuaca tidak berpengaruh signifikan terhadap penggunaan sepeda.
                                    ''')
                            
                            with st.expander('Multi Kategori-Multi Kategori') :
                                st.markdown('''  
                                        
                                            - **Korelasi antara Musim (season) dan Bulan (mnth)**  
                                                Korelasi sangat tinggi (0.8965), menunjukkan bahwa musim dan bulan sangat terkait, dengan pola penggunaan sepeda yang konsisten sepanjang tahun.

                                            - **Korelasi antara Hari dalam Minggu (weekday) dan Variabel Lain**  
                                                Korelasi sangat rendah dengan musim (0.0157) dan bulan (0.0289), menunjukkan bahwa hari dalam minggu tidak banyak dipengaruhi oleh musim atau bulan.

                                            - **Korelasi antara Cuaca (weathersit) dan Variabel Lain**  
                                                Korelasi rendah dengan musim (0.0569), bulan (0.0892), dan hari dalam minggu (0.0469), menunjukkan bahwa cuaca tidak berpengaruh signifikan terhadap pola penggunaan sepeda.

                                            - **Korelasi antara Tanggal (date) dan Variabel Lain**  
                                                Korelasi rendah dengan musim (0.0427), bulan (0.0407), dan hari dalam minggu (0.0909), menunjukkan bahwa tanggal tidak memiliki pengaruh signifikan terhadap pola penggunaan sepeda.
                                        ''')

        options = [option + ' ' * (i+1) for option in options]
        
elif menu == 'Explanatory Dashboard' :

    
    with st.container() :
        st.markdown("<h3 style='text-align: center;'>Tren Total Penyewaan Berdasarkan Waktu</h3>", unsafe_allow_html=True)
        st.write(pertanyaan_1(day_dash))
        
        with st.expander('Insights') :
            st.markdown('''
                    <div style="text-align: justify;"> 
                     Tren total penyewaan menunjukkan peningkatan yang signifikan dari tahun 2011 ke 2012, dengan tahun 2012 mencatat rata-rata penyewaan yang lebih tinggi secara keseluruhan. 
                     Pola penyewaan bulanan di kedua tahun tersebut menunjukkan kemiripan, tetapi 2012 selalu berada di atas rata-rata keseluruhan, mencerminkan pertumbuhan minat terhadap penyewaan sepeda. 
                     Desember 2012 menonjol sebagai bulan dengan penyewaan tertinggi, sementara Mei menjadi bulan terendah di kedua tahun. Dalam skala harian, Rabu adalah hari dengan penyewaan tertinggi di 2012, 
                     sedangkan Selasa mencatat angka terendah. Pada tingkat tanggal, tanggal 17 di 2012 dan tanggal 30 di 2011 masing-masing menunjukkan penyewaan tertinggi, menunjukkan bahwa faktor waktu berperan 
                     penting dalam tren penyewaan. Secara keseluruhan, data ini mengindikasikan bahwa penyewaan sepeda dipengaruhi oleh berbagai faktor temporal, dengan puncak pada waktu-waktu tertentu dan pola pertumbuhan positif dari tahun ke tahun.
                     
                     </div>
                     ''', unsafe_allow_html = True)

    with st.container() :
        st.markdown("<h3 style='text-align: center;'>Tren Penyewaan Sepeda Setiap Musim Berdasarkan Jam</h3>", unsafe_allow_html=True)
        st.write(pertanyaan_3(hour_dash))
        
        with st.expander('Insights') :
            st.markdown('''
                    <div style="text-align: justify;"> 
                    Tren penyewaan sepeda berdasarkan jam dan musim menunjukkan pola yang konsisten di mana waktu sore, khususnya antara pukul 17.00 dan 18.00, 
                    menjadi puncak penyewaan di semua musim. Pukul 08.00 juga menonjol sebagai waktu penyewaan tinggi, meskipun tidak dalam musim fall. Secara 
                    keseluruhan, meskipun terdapat variasi musiman, pola penyewaan cenderung mirip, menunjukkan bahwa jam-jam sibuk di pagi dan sore hari menjadi 
                    saat favorit bagi pengguna sepeda. Musim fall khususnya menonjol dengan puncak penyewaan di sore hari, menandakan bahwa faktor waktu sangat 
                    berpengaruh terhadap tingkat penyewaan sepeda sepanjang tahun.  
                    
                    </div>
                    ''', unsafe_allow_html = True)
    
    with st.container() :
        st.markdown("<h3 style='text-align: center;'>Hubungan Antara Kolom Temp, Atemp, Windspeed, dan Hum dengan Total Penyewaan</h3>", unsafe_allow_html=True)
        st.write(pertanyaan_2(day_dash))
        
        with st.expander('Insights') :
            st.markdown('''
                    <div style="text-align: justify;"> 
                    Hubungan antara variabel cuaca dan total penyewaan sepeda menunjukkan pola yang signifikan. Suhu (temp) dan suhu terasa (atemp) memiliki korelasi positif yang kuat dengan jumlah penyewaan, 
                    menandakan bahwa cuaca yang lebih hangat dan nyaman mendorong orang untuk menyewa sepeda. Sebaliknya, kecepatan angin (windspeed) memiliki korelasi negatif yang sedang, menunjukkan bahwa 
                    semakin tinggi kecepatan angin, semakin sedikit orang yang cenderung menyewa sepeda. Kelembaban (hum) menunjukkan korelasi negatif yang sangat lemah dengan jumlah penyewaan, sehingga pengaruhnya 
                    terhadap keputusan penyewaan sepeda hampir tidak signifikan. Secara keseluruhan, data ini menunjukkan bahwa suhu dan kondisi cuaca yang nyaman berkontribusi pada peningkatan penyewaan, sementara 
                    angin kencang dapat mengurangi minat orang untuk menyewa sepeda. 
                     
                     </div>
                     ''', unsafe_allow_html = True)

    with st.container() :
        st.markdown("<h3 style='text-align: center;'>Tren Penyewaan Sepeda Setiap Hari Berdasarkan Jam</h3>", unsafe_allow_html=True)
        st.write(pertanyaan_4(hour_dash, hour_df))
        
        with st.expander('Insights') :
            st.markdown('''
                    <div style="text-align: justify;"> 
                    Tren penyewaan sepeda berdasarkan jam dan hari menunjukkan perbedaan signifikan antara hari kerja dan akhir pekan. Pukul 00.00 hingga 05.00 mencatat penyewaan terendah pada hari kerja, namun mengalami 
                    peningkatan di akhir pekan. Waktu puncak penyewaan pada hari kerja terjadi di pukul 08.00, 17.00, dan 18.00, mencerminkan jam sibuk bagi pengguna sepeda. Di hari Sabtu, puncak penyewaan tertinggi tercatat 
                    antara pukul 13.00 hingga 15.00, sementara pada hari Minggu, periode puncak berlangsung antara pukul 12.00 hingga 14.00. Secara keseluruhan, hari Jumat menunjukkan rata-rata penyewaan tertinggi, diikuti oleh 
                    Kamis dan Sabtu, menandakan bahwa pola penyewaan dipengaruhi oleh hari dalam seminggu dan waktu tertentu sepanjang hari.
                     </div>
                     ''', unsafe_allow_html = True)
